import { Stethoscope } from "lucide-react";

import type { FeaturedDoctor } from "../types/doctor";

export const FEATURED_DOCTORS: FeaturedDoctor[] = [
  {
    id: "1",
    name: "Dr. John Smith",
    specialty: "Cardiology",
    experience: "10+ Years Experience",
    href: "/doctors/1",
    icon: Stethoscope,
  },
  {
    id: "2",
    name: "Dr. Sarah Johnson",
    specialty: "Dermatology",
    experience: "8+ Years Experience",
    href: "/doctors/2",
    icon: Stethoscope,
  },
  {
    id: "3",
    name: "Dr. Michael Brown",
    specialty: "Pediatrics",
    experience: "12+ Years Experience",
    href: "/doctors/3",
    icon: Stethoscope,
  },
  {
    id: "4",
    name: "Dr. Emily Davis",
    specialty: "Neurology",
    experience: "15+ Years Experience",
    href: "/doctors/4",
    icon: Stethoscope,
  },
  {
    id: "5",
    name: "Dr. David Wilson",
    specialty: "Orthopedics",
    experience: "9+ Years Experience",
    href: "/doctors/5",
    icon: Stethoscope,
  },
  {
    id: "6",
    name: "Dr. Jessica Miller",
    specialty: "Ophthalmology",
    experience: "7+ Years Experience",
    href: "/doctors/6",
    icon: Stethoscope,
  },
  {
    id: "7",
    name: "Dr. Christopher Moore",
    specialty: "ENT",
    experience: "11+ Years Experience",
    href: "/doctors/7",
    icon: Stethoscope,
  },
  {
    id: "8",
    name: "Dr. Olivia Taylor",
    specialty: "Gynecology",
    experience: "13+ Years Experience",
    href: "/doctors/8",
    icon: Stethoscope,
  },
  {
    id: "9",
    name: "Dr. Daniel Anderson",
    specialty: "Psychiatry",
    experience: "10+ Years Experience",
    href: "/doctors/9",
    icon: Stethoscope,
  },
  {
    id: "10",
    name: "Dr. Sophia Thomas",
    specialty: "Endocrinology",
    experience: "6+ Years Experience",
    href: "/doctors/10",
    icon: Stethoscope,
  },
  {
    id: "11",
    name: "Dr. James White",
    specialty: "Urology",
    experience: "14+ Years Experience",
    href: "/doctors/11",
    icon: Stethoscope,
  },
  {
    id: "12",
    name: "Dr. Ava Martinez",
    specialty: "General Medicine",
    experience: "5+ Years Experience",
    href: "/doctors/12",
    icon: Stethoscope,
  },
];