import { DoctorAppointment } from "../types/appointment";


export const MOCK_APPOINTMENTS: DoctorAppointment[] = [
  {
    id: "1",
    patientName: "Nguyen Van A",
    patientId: "P001",
    date: "2026-08-07",
    time: "09:00",
    reason: "General Checkup",
    status: "confirmed",
  },
  {
    id: "2",
    patientName: "Tran Thi B",
    patientId: "P002",
    date: "2026-08-07",
    time: "10:30",
    reason: "Follow-up",
    status: "pending",
  },
  {
    id: "3",
    patientName: "Le Van C",
    patientId: "P003",
    date: "2026-08-07",
    time: "13:00",
    reason: "Blood Test Review",
    status: "completed",
  },
  {
    id: "4",
    patientName: "Pham Thi D",
    patientId: "P004",
    date: "2026-08-08",
    time: "08:30",
    reason: "Heart Checkup",
    status: "confirmed",
  },
  {
    id: "5",
    patientName: "Hoang Van E",
    patientId: "P005",
    date: "2026-08-08",
    time: "09:45",
    reason: "General Consultation",
    status: "pending",
  },
  {
    id: "6",
    patientName: "Vo Thi F",
    patientId: "P006",
    date: "2026-08-08",
    time: "11:00",
    reason: "Medicine Follow-up",
    status: "cancelled",
  },
  {
    id: "7",
    patientName: "Dang Van G",
    patientId: "P007",
    date: "2026-08-09",
    time: "14:00",
    reason: "Health Screening",
    status: "confirmed",
  },
  {
    id: "8",
    patientName: "Bui Thi H",
    patientId: "P008",
    date: "2026-08-09",
    time: "15:30",
    reason: "Chronic Disease Check",
    status: "completed",
  },
  {
    id: "9",
    patientName: "Do Van I",
    patientId: "P009",
    date: "2026-08-10",
    time: "08:00",
    reason: "General Checkup",
    status: "pending",
  },
  {
    id: "10",
    patientName: "Nguyen Thi J",
    patientId: "P010",
    date: "2026-08-10",
    time: "10:15",
    reason: "Dental Consultation",
    status: "confirmed",
  },
  {
    id: "11",
    patientName: "Tran Van K",
    patientId: "P011",
    date: "2026-08-11",
    time: "09:30",
    reason: "Health Consultation",
    status: "completed",
  },
  {
    id: "12",
    patientName: "Le Thi L",
    patientId: "P012",
    date: "2026-08-11",
    time: "13:45",
    reason: "Prescription Review",
    status: "pending",
  },
  {
    id: "13",
    patientName: "Pham Van M",
    patientId: "P013",
    date: "2026-08-12",
    time: "14:30",
    reason: "Vaccination",
    status: "cancelled",
  },
  {
    id: "14",
    patientName: "Hoang Thi N",
    patientId: "P014",
    date: "2026-08-12",
    time: "16:00",
    reason: "Follow-up",
    status: "confirmed",
  },
  {
    id: "15",
    patientName: "Vu Van O",
    patientId: "P015",
    date: "2026-08-13",
    time: "11:30",
    reason: "Medical Consultation",
    status: "pending",
  },
];