import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/features/auth/providers/auth-provider";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import { CustomerFooter } from "@/features/customers/components/customer-footer";
import { CustomerHeader } from "@/features/customers/components/customer-header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doctor manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <AuthProvider>
          <Providers>
            <div className="flex min-h-screen flex-col">
              <CustomerHeader />

              <main className="flex-1">
                {children}
              </main>

              <CustomerFooter />
            </div>

            <Toaster />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
